math = ["","ARITHMETICS","TRIGONOMETRY","CALCULUS","QUADRATIC EQUATION","CONVERSIONS"]

arith = ["","ADDITION","SUBTRACTION","MULTIPLICATION","DIVISION","MODULUS"]

trig = ["","COSINE","SINE","TANGENT","SECANT","COSECANT","COTANGENT"]
    
calc = ["","LOGARITHM","ROOT","LCM & GCF"]

weight = ["","KILOGRAMS","GRAMS","POUNDS","OUNCES"]

distance = ["","KILOMETRES","METRES","MILES"]

temperature = ["","CELCIUS","FAHREINHEIT","KELVIN"]